# Generated by Django 3.1.7 on 2021-03-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_roomservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name', 'price', 'description']},
        ),
    ]
