# Generated by Django 3.1.7 on 2021-03-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20210330_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(default='defo', upload_to='images/'),
        ),
    ]
