# Generated by Django 3.1.7 on 2021-03-31 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_roomservice_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
