# Generated by Django 3.1.7 on 2021-03-31 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('deperture_date', models.DateField(blank=True, null=True)),
                ('number_rooms', models.CharField(max_length=2)),
                ('guest', models.CharField(max_length=2)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room')),
            ],
        ),
    ]
