# Generated by Django 3.1.7 on 2021-03-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='baby_bed',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='convience_store',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomservice',
            name='swimming_pool',
            field=models.BooleanField(blank=True),
        ),
    ]
