# Generated by Django 3.1.7 on 2021-03-31 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20210331_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.booking'),
        ),
    ]
