# Generated by Django 3.1.7 on 2021-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_remove_booking_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='diff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
