# Generated by Django 3.1.7 on 2021-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_auto_20210401_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='diff',
            field=models.DateField(blank=True, null=True),
        ),
    ]
