# Generated by Django 3.1.7 on 2021-04-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_auto_20210401_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='diff',
        ),
    ]
