# Generated by Django 3.1.7 on 2021-04-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_remove_booking_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='diff',
            field=models.DateField(blank=True, null=True),
        ),
    ]
