# Generated by Django 3.1.7 on 2021-04-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_auto_20210401_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurants',
        ),
    ]
