# Generated by Django 3.1.7 on 2021-04-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_delete_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='diff',
        ),
    ]
