# Generated by Django 3.1.7 on 2021-04-02 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0028_booking_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_customer',
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
