# Generated by Django 3.1.7 on 2021-04-05 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_auto_20210402_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 14, 34, 48, 566267)),
        ),
    ]
